use_frameworks!

platform :ios, '8.0'

target 'ECharts_oc_Example' do
  pod 'ECharts_oc', :path => '../'

  target 'ECharts_oc_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
